### ISSUE TITLE
 Migrate QDM Microscopy Data Storage to fatiando-data

### ISSUE THREAD

**Issue by YagoMCastro** [fatiando/magali#32]
We are currently experiencing failures in the tests due to issues with downloading QDM microscopy data from Figshare. It seems that Figshare is denying data downloads after a certain number of requests, which is causing the tests to fail.

**Proposed Solution:**

To resolve this, we should switch from using Figshare to storing the QDM microscopy data in the `fatiando-data` repository. This will provide more control over the data access and improve reliability in our tests.

**Tasks:**
1. Migrate the QDM microscopy data to `fatiando-data`.
2. Update the tests to download the data from `fatiando-data` instead of Figshare.
3. Ensure all tests pass with the new data source.

**Comment by leouieda** [comment]
@YagoMCastro were tasks 2 and 3 done as well? It’s good to leave a comment when closing an issue linking to PRs and etc that actually implemented the fix or stating that it won’t be fixed and why.

**Comment by YagoMCastro** [comment]
Sorry about that. After thinking more about this issue, I realized it might be more related to `fatiando-data`. So I figured this issue should be  more related to `Magali` stuff  instead. Maybe it would be best to just edit this issue, but I mistakenly decided to create a new one. [Magali issue #35](https://github.com/fatiando/magali/issues/35).

**Comment by leouieda** [comment]
👍🏾 no problem, just checking
